In [1]:
import torch

/home/seonggye/.local/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.cuda.is_available()

True

## 4.1 Tensor : 데이터를 표현하는 단위

In [4]:
# Scalar
scalar1 = torch.tensor([1.0])
scalar1

tensor([1.])

In [5]:
# Vector
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([2,4,6])

In [7]:
torch.div(vector1,vector2)

tensor([0.5000, 0.5000, 0.5000])

In [10]:
# matrix
matrix1 = torch.tensor([[1,2],[3,4]])
matrix2 = torch.tensor([[5,6],[7,8]])

In [13]:
torch.matmul(matrix1,matrix2)

tensor([[19, 22],
        [43, 50]])

In [14]:
# tensor -> 2차원 이상의 배열
tensor1 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor2 = torch.tensor([[[9,10],[11,12]],[[13,14],[15,16]]])


In [16]:
torch.mul(tensor1,tensor2)

tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])

In [17]:
torch.matmul(tensor1,tensor2)

tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])

## 4.2 Autograd -> back propagation을 이용해 파라미터를 업데이트 하는 방법

In [18]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [21]:
batch_size = 64
input_size = 1000
hidden_size = 100
output_size =10

In [26]:
# input, output, weight 정의
x = torch.randn(batch_size,input_size, device=DEVICE, dtype=float, requires_grad=False)
y = torch.randn(batch_size,output_size, device=DEVICE, dtype=float, requires_grad=False)
w1 = torch.randn(input_size, hidden_size, device=DEVICE, dtype=float, requires_grad=True)
w2 = torch.randn(hidden_size, output_size, device=DEVICE, dtype=float, requires_grad=True)

In [28]:
lr = 1e-6
for t in range(1,501):
    y_pred = x.mm(w1).clamp(min=0).mm(w2) # clamp는 activation function

    loss = (y-y_pred).pow(2).sum() # mse loss
    if t%100 ==0:
        print("Iter:",t, "\t", "Loss :",loss)
    
    loss.backward()

    with torch.no_grad():
        w1 -= lr * w1.grad
        w2 -= lr * w2.grad

        w1.grad.zero_()
        w2.grad.zero_()

Iter: 100 	 Loss : tensor(1.4577e-06, device='cuda:0', dtype=torch.float64,
       grad_fn=<SumBackward0>)
Iter: 200 	 Loss : tensor(3.1005e-08, device='cuda:0', dtype=torch.float64,
       grad_fn=<SumBackward0>)
Iter: 300 	 Loss : tensor(6.6544e-10, device='cuda:0', dtype=torch.float64,
       grad_fn=<SumBackward0>)
Iter: 400 	 Loss : tensor(1.4360e-11, device='cuda:0', dtype=torch.float64,
       grad_fn=<SumBackward0>)
Iter: 500 	 Loss : tensor(3.1094e-13, device='cuda:0', dtype=torch.float64,
       grad_fn=<SumBackward0>)
